server:
  port: 50011
spring:
  application:
    name: client-producer
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codeforfun-discovery
