server:
  port: 50021
spring:
  application:
    name: client-consumer
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codeforfun-discovery
#logging:
#  level:
#    root: debug